# init_db.py

from apps import create_app, db
from apps.customer.models import Customer
from apps.employee.models import Employee
from apps.product.models import Products
from apps.sale.models import SaleOrder, OrderDetails
from apps.authentication.models import Users
from datetime import datetime, timedelta
from apps.config import config_dict
import os

DEBUG = (os.getenv('DEBUG', 'False') == 'True')

# The configuration
get_config_mode = 'Debug'

try:
    # Load the configuration using the default values
    app_config = config_dict[get_config_mode.capitalize()]
except KeyError:
    exit('Error: Invalid <config_mode>. Expected values [Debug, Production]')

app = create_app(app_config)

with app.app_context():
    db.create_all()
    #drop all user
    db.session.query(Users).delete()
    db.session.query(Customer).delete()
    db.session.query(Employee).delete()
    db.session.query(Products).delete()
    db.session.query(SaleOrder).delete()
    db.session.query(OrderDetails).delete()
    db.session.commit()
    # Add user admin pass admin
    user = Users(username='admin', password='admin', email='admin@uit')
    db.session.add(user)
    db.session.commit()

    # Add sample customers
    customer1 = Customer(name='Phạm Văn A', phone='123-456-7890', email='apham@example.com', address='123 Main St')
    customer2 = Customer(name='Nguyễn Thị B', phone='987-654-3210', email='bnguyen@example.com', address='456 Elm St')
    customer3 = Customer(name='Trần Văn C', phone='555-123-4567', email='ctran@gmail.com', address='789 Maple St')
    customer4 = Customer(name='Lê Thị D', phone='555-987-6543', email='dle@gmail.com', address='321 Oak St')
    customer5 = Customer(name='Nguyễn Văn E', phone='555-555-5555', email='enguyen@gmail.com', address='654 Pine St')
    customer6 = Customer(name='Trần Thị F', phone='555-123-4567', email='ftran@gmail.com', address='987 Cedar St')
    customer7 = Customer(name='Lê Văn G', phone='555-987-6543', email='gle@gmail.com', address='147 Birch St')
    customer8 = Customer(name='Phạm Thị H', phone='555-555-5555', email='hpham@gmail.com', address='258 Spruce St')
    customer9 = Customer(name='Nguyễn Văn I', phone='555-123-4567', email='inguyen@gmail.com', address='369 Ash St')
    customer10 = Customer(name='Trần Thị K', phone='555-987-6543', email='ktran@gmail.com', address='654 Pine St')
    customer11 = Customer(name='Lê Văn L', phone='555-555-5555', email='lle@gmail.com', address='987 Cedar St')
    customer12 = Customer(name='Phạm Thị M', phone='555-123-4567', email='mpham@gmail.com', address='147 Birch St')
    db.session.add(customer1)
    db.session.add(customer2)
    db.session.add(customer3)
    db.session.add(customer4)
    db.session.add(customer5)
    db.session.add(customer6)
    db.session.add(customer7)
    db.session.add(customer8)
    db.session.add(customer9)
    db.session.add(customer10)
    db.session.add(customer11)
    db.session.add(customer12)

    # Add sample employees
    employee1 = Employee(name='Sơn Phạm', position='Admin', phone='555-123-4567', email='23730043@uit.edu.vn',
                         hire_date=datetime.strptime('2023-01-01', '%Y-%m-%d').date())
    employee2 = Employee(name='Linh Nguyễn', position='Sales', phone='555-987-6543', email='23730027@uit.edu.vn',
                         hire_date=datetime.strptime('2023-02-01', '%Y-%m-%d').date())
    employee3 = Employee(name='Vũ Lê', position='Sales', phone='555-987-6543', email='23730058@uit.edu.vn',
                         hire_date=datetime.strptime('2023-02-01', '%Y-%m-%d').date())
    employee4 = Employee(name='Thiện Trần', position='Sales', phone='555-987-6543', email='thientran@example.com',
                         hire_date=datetime.strptime('2023-02-01', '%Y-%m-%d').date())
    employee5 = Employee(name='Hải Nguyễn', position='Sales', phone='555-987-6543', email='hainguyen@example.com',
                         hire_date=datetime.strptime('2023-02-01', '%Y-%m-%d').date())


    db.session.add(employee1)
    db.session.add(employee2)
    db.session.add(employee3)
    db.session.add(employee4)
    db.session.add(employee5)

    # Add sample products
    product1 = Products(name='IPhone 16 Pro Max', description='This is an example description for Iphone 16 ProMax, make the description a little bit longer to show off in the free text field', price=30000000, stock=100)
    product2 = Products(name='Samsung Fold 6', description='This is an example description for Samsung Fold 6, make the description a little bit longer to show off in the free text field', price=41000000, stock=200)
    product3 = Products(name='Xiaomi 12', description='This is an example description for Xiaomi 12, make the description a little bit longer to show off in the free text field', price=15000000, stock=300)
    product4 = Products(name='Oppo Reno 7', description='This is an example description for Oppo Reno 7, make the description a little bit longer to show off in the free text field', price=12000000, stock=400)
    product5 = Products(name='Vivo V23', description='This is an example description for Vivo V23, make the description a little bit longer to show off in the free text field', price=8000000, stock=500)
    product6 = Products(name='Realme 9', description='This is an example description for Realme 9, make the description a little bit longer to show off in the free text field', price=7000000, stock=600)
    product7 = Products(name='Nokia 9', description='This is an example description for Nokia 9, make the description a little bit longer to show off in the free text field', price=9000000, stock=700)
    product8 = Products(name='Huawei P50', description='This is an example description for Huawei P50, make the description a little bit longer to show off in the free text field', price=11000000, stock=800)
    product9 = Products(name='Sony Xperia 5', description='This is an example description for Sony Xperia 5, make the description a little bit longer to show off in the free text field', price=13000000, stock=900)
    product10 = Products(name='LG V60', description='This is an example description for LG V60, make the description a little bit longer to show off in the free text field', price=10000000, stock=1000)
    product11 = Products(name='Asus Zenfone 8', description='This is an example description for Asus Zenfone 8, make the description a little bit longer to show off in the free text field', price=14000000, stock=1100)
    product12 = Products(name='Google Pixel 6', description='This is an example description for Google Pixel 6, make the description a little bit longer to show off in the free text field', price=16000000, stock=1200)

    db.session.add(product1)
    db.session.add(product2)
    db.session.add(product3)
    db.session.add(product4)
    db.session.add(product5)
    db.session.add(product6)
    db.session.add(product7)
    db.session.add(product8)
    db.session.add(product9)
    db.session.add(product10)
    db.session.add(product11)
    db.session.add(product12)

    db.session.commit()
    # Add sample sale orders
    order1 = SaleOrder(customer_id=customer1.customer_id, order_date=datetime.strptime('2024-06-01', '%Y-%m-%d').date(), total_amount=product1.price * 5,
                       employee_id=employee2.employee_id)
    db.session.add(order1)
    db.session.commit()
    order_detail1 = OrderDetails(order_id=order1.id, product_id=product1.product_id, quantity=5, unit_price=product1.price)
    db.session.add(order_detail1)
    order2 = SaleOrder(customer_id=customer2.customer_id, order_date=datetime.strptime('2024-06-02', '%Y-%m-%d').date(), total_amount=product2.price * 10,
                       employee_id=employee3.employee_id)
    db.session.add(order2)
    db.session.commit()
    order_detail2 = OrderDetails(order_id=order2.id, product_id=product2.product_id, quantity=10, unit_price=product2.price)
    db.session.add(order_detail2)
    order3 = SaleOrder(customer_id=customer3.customer_id, order_date=datetime.strptime('2024-07-03', '%Y-%m-%d').date(), total_amount=product3.price * 15,
                          employee_id=employee4.employee_id)
    db.session.add(order3)
    db.session.commit()
    order_detail3 = OrderDetails(order_id=order3.id, product_id=product3.product_id, quantity=15, unit_price=product3.price)
    db.session.add(order_detail3)
    order4 = SaleOrder(customer_id=customer4.customer_id, order_date=datetime.strptime('2024-07-04', '%Y-%m-%d').date(), total_amount=product4.price * 20,
                          employee_id=employee5.employee_id)
    db.session.add(order4)
    db.session.commit()
    order_detail4 = OrderDetails(order_id=order4.id, product_id=product4.product_id, quantity=20, unit_price=product4.price)
    db.session.add(order_detail4)
    order5 = SaleOrder(customer_id=customer5.customer_id, order_date=datetime.strptime('2024-07-05', '%Y-%m-%d').date(), total_amount=product5.price * 25,
                          employee_id=employee1.employee_id)
    db.session.add(order5)
    db.session.commit()
    order_detail5 = OrderDetails(order_id=order5.id, product_id=product5.product_id, quantity=25, unit_price=product5.price)
    db.session.add(order_detail5)
    order6 = SaleOrder(customer_id=customer6.customer_id, order_date=datetime.strptime('2024-08-06', '%Y-%m-%d').date(), total_amount=product6.price * 30,
                          employee_id=employee2.employee_id)
    db.session.add(order6)
    db.session.commit()
    order_detail6 = OrderDetails(order_id=order6.id, product_id=product6.product_id, quantity=30, unit_price=product6.price)
    db.session.add(order_detail6)
    order7 = SaleOrder(customer_id=customer7.customer_id, order_date=datetime.strptime('2024-08-07', '%Y-%m-%d').date(), total_amount=product7.price * 35,
                          employee_id=employee3.employee_id)
    db.session.add(order7)
    db.session.commit()
    order_detail7 = OrderDetails(order_id=order7.id, product_id=product7.product_id, quantity=35, unit_price=product7.price)
    db.session.add(order_detail7)
    order8 = SaleOrder(customer_id=customer8.customer_id, order_date=datetime.strptime('2024-08-08', '%Y-%m-%d').date(), total_amount=product8.price * 40,
                          employee_id=employee4.employee_id)
    db.session.add(order8)
    db.session.commit()
    order_detail8 = OrderDetails(order_id=order8.id, product_id=product8.product_id, quantity=40, unit_price=product8.price)
    db.session.add(order_detail8)
    order9 = SaleOrder(customer_id=customer9.customer_id, order_date=datetime.strptime('2024-09-09', '%Y-%m-%d').date(), total_amount=product9.price * 45,
                          employee_id=employee5.employee_id)
    db.session.add(order9)
    db.session.commit()
    order_detail9 = OrderDetails(order_id=order9.id, product_id=product9.product_id, quantity=45, unit_price=product9.price)
    db.session.add(order_detail9)
    order10 = SaleOrder(customer_id=customer10.customer_id, order_date=datetime.strptime('2024-09-10', '%Y-%m-%d').date(), total_amount=product10.price * 50,
                          employee_id=employee1.employee_id)
    db.session.add(order10)
    db.session.commit()
    order_detail10 = OrderDetails(order_id=order10.id, product_id=product10.product_id, quantity=50, unit_price=product10.price)
    db.session.add(order_detail10)
    order11 = SaleOrder(customer_id=customer11.customer_id, order_date=datetime.strptime('2024-10-11', '%Y-%m-%d').date(), total_amount=product11.price * 55,
                          employee_id=employee2.employee_id)
    db.session.add(order11)
    db.session.commit()
    order_detail11 = OrderDetails(order_id=order11.id, product_id=product11.product_id, quantity=55, unit_price=product11.price)
    db.session.add(order_detail11)
    order12 = SaleOrder(customer_id=customer12.customer_id, order_date=datetime.strptime('2024-10-12', '%Y-%m-%d').date(), total_amount=product12.price * 60,
                          employee_id=employee3.employee_id)
    db.session.add(order12)
    db.session.commit()
    order_detail12 = OrderDetails(order_id=order12.id, product_id=product12.product_id, quantity=60, unit_price=product12.price)
    db.session.add(order_detail12)
    order13 = SaleOrder(customer_id=customer1.customer_id, order_date=datetime.strptime('2024-10-13', '%Y-%m-%d').date(), total_amount=product1.price * 65,
                            employee_id=employee4.employee_id)
    db.session.add(order13)
    db.session.commit()
    order_detail13 = OrderDetails(order_id=order13.id, product_id=product1.product_id, quantity=65, unit_price=product1.price)
    db.session.add(order_detail13)
    order14 = SaleOrder(customer_id=customer2.customer_id, order_date=datetime.strptime('2024-11-14', '%Y-%m-%d').date(), total_amount=product2.price * 70,
                            employee_id=employee5.employee_id)
    db.session.add(order14)
    db.session.commit()
    order_detail14 = OrderDetails(order_id=order14.id, product_id=product2.product_id, quantity=70, unit_price=product2.price)
    db.session.add(order_detail14)
    order15 = SaleOrder(customer_id=customer3.customer_id, order_date=datetime.strptime('2024-11-15', '%Y-%m-%d').date(), total_amount=product3.price * 75,
                            employee_id=employee1.employee_id)
    db.session.add(order15)
    db.session.commit()
    order_detail15 = OrderDetails(order_id=order15.id, product_id=product3.product_id, quantity=75, unit_price=product3.price)
    db.session.add(order_detail15)
    order16 = SaleOrder(customer_id=customer4.customer_id, order_date=datetime.strptime('2024-11-16', '%Y-%m-%d').date(), total_amount=product4.price * 80,
                            employee_id=employee1.employee_id)
    db.session.add(order16)
    db.session.commit()
    order_detail16 = OrderDetails(order_id=order16.id, product_id=product4.product_id, quantity=80, unit_price=product4.price)
    db.session.add(order_detail16)
    order17 = SaleOrder(customer_id=customer5.customer_id, order_date=datetime.strptime('2024-11-17', '%Y-%m-%d').date(), total_amount=product5.price * 85,
                            employee_id=employee2.employee_id)
    db.session.add(order17)
    db.session.commit()
    order_detail17 = OrderDetails(order_id=order17.id, product_id=product5.product_id, quantity=85, unit_price=product5.price)
    db.session.add(order_detail17)
    order18 = SaleOrder(customer_id=customer6.customer_id, order_date=datetime.strptime('2024-12-18', '%Y-%m-%d').date(), total_amount=product6.price * 90,
                            employee_id=employee1.employee_id)
    db.session.add(order18)
    db.session.commit()
    order_detail18 = OrderDetails(order_id=order18.id, product_id=product6.product_id, quantity=90, unit_price=product6.price)
    db.session.add(order_detail18)
    order19 = SaleOrder(customer_id=customer7.customer_id, order_date=datetime.strptime('2024-12-19', '%Y-%m-%d').date(), total_amount=product7.price * 95,
                            employee_id=employee2.employee_id)
    db.session.add(order19)
    db.session.commit()
    order_detail19 = OrderDetails(order_id=order19.id, product_id=product7.product_id, quantity=95, unit_price=product7.price)
    db.session.add(order_detail19)
    order20 = SaleOrder(customer_id=customer8.customer_id, order_date=datetime.strptime('2024-12-20', '%Y-%m-%d').date(), total_amount=product8.price * 10,
                            employee_id=employee1.employee_id)
    db.session.add(order20)
    db.session.commit()
    order_detail20 = OrderDetails(order_id=order20.id, product_id=product8.product_id, quantity=10, unit_price=product8.price)
    db.session.add(order_detail20)
    order21 = SaleOrder(customer_id=customer9.customer_id, order_date=datetime.strptime('2024-12-21', '%Y-%m-%d').date(), total_amount=product9.price * 15,
                            employee_id=employee2.employee_id)
    db.session.add(order21)
    db.session.commit()
    order_detail21 = OrderDetails(order_id=order21.id, product_id=product9.product_id, quantity=15, unit_price=product9.price)
    db.session.add(order_detail21)
    order22 = SaleOrder(customer_id=customer10.customer_id, order_date=datetime.strptime('2024-12-22', '%Y-%m-%d').date(), total_amount=product10.price * 11,
                            employee_id=employee3.employee_id)
    db.session.add(order22)
    db.session.commit()
    order_detail22 = OrderDetails(order_id=order22.id, product_id=product10.product_id, quantity=11, unit_price=product10.price)
    db.session.add(order_detail22)
    order23 = SaleOrder(customer_id=customer11.customer_id, order_date=datetime.strptime('2024-12-23', '%Y-%m-%d').date(), total_amount=product11.price * 11,
                            employee_id=employee4.employee_id)
    db.session.add(order23)
    db.session.commit()
    order_detail23 = OrderDetails(order_id=order23.id, product_id=product11.product_id, quantity=11, unit_price=product11.price)
    db.session.add(order_detail23)
    order24 = SaleOrder(customer_id=customer12.customer_id, order_date=datetime.strptime('2024-12-24', '%Y-%m-%d').date(), total_amount=product12.price * 12,
                            employee_id=employee5.employee_id)
    db.session.add(order24)
    db.session.commit()
    order_detail24 = OrderDetails(order_id=order24.id, product_id=product12.product_id, quantity=12, unit_price=product12.price)
    db.session.add(order_detail24)
    order25 = SaleOrder(customer_id=customer1.customer_id, order_date=datetime.strptime('2024-12-25', '%Y-%m-%d').date(), total_amount=product1.price * 15 + product2.price * 15,
                            employee_id=employee1.employee_id)
    db.session.add(order25)
    db.session.commit()
    order_detail25 = OrderDetails(order_id=order25.id, product_id=product1.product_id, quantity=15, unit_price=product1.price)
    db.session.add(order_detail25)
    order_detail25_2 = OrderDetails(order_id=order25.id, product_id=product2.product_id, quantity=15, unit_price=product2.price)
    db.session.add(order_detail25_2)
    order26 = SaleOrder(customer_id=customer2.customer_id, order_date=datetime.strptime('2024-12-26', '%Y-%m-%d').date(), total_amount=product2.price * 13 + product3.price * 13,
                            employee_id=employee1.employee_id)
    db.session.add(order26)
    db.session.commit()
    order_detail26 = OrderDetails(order_id=order26.id, product_id=product2.product_id, quantity=13, unit_price=product2.price)
    db.session.add(order_detail26)
    order_detail26_2 = OrderDetails(order_id=order26.id, product_id=product3.product_id, quantity=13, unit_price=product3.price)
    db.session.add(order_detail26_2)
    order27 = SaleOrder(customer_id=customer3.customer_id, order_date=datetime.strptime('2024-12-27', '%Y-%m-%d').date(), total_amount=product3.price * 15 + product4.price * 13,
                            employee_id=employee2.employee_id)
    db.session.add(order27)
    db.session.commit()
    order_detail27 = OrderDetails(order_id=order27.id, product_id=product3.product_id, quantity=15, unit_price=product3.price)
    db.session.add(order_detail27)
    order_detail27_2 = OrderDetails(order_id=order27.id, product_id=product4.product_id, quantity=13, unit_price=product4.price)
    db.session.add(order_detail27_2)
    db.session.commit()
    order27 = SaleOrder(customer_id=customer3.customer_id, order_date=datetime.strptime('2024-06-27', '%Y-%m-%d').date(), total_amount=product3.price * 13 + product4.price * 15,
                            employee_id=employee2.employee_id)
    db.session.add(order27)
    db.session.commit()
    order_detail27 = OrderDetails(order_id=order27.id, product_id=product3.product_id, quantity=13, unit_price=product3.price)
    db.session.add(order_detail27)
    order_detail27_2 = OrderDetails(order_id=order27.id, product_id=product4.product_id, quantity=15, unit_price=product4.price)
    db.session.add(order_detail27_2)
    order28 = SaleOrder(customer_id=customer4.customer_id, order_date=datetime.strptime('2024-06-28', '%Y-%m-%d').date(), total_amount=product4.price * 14 + product5.price * 14,
                            employee_id=employee3.employee_id)
    db.session.add(order28)
    db.session.commit()
    order_detail28 = OrderDetails(order_id=order28.id, product_id=product4.product_id, quantity=14, unit_price=product4.price)
    db.session.add(order_detail28)
    order_detail28_2 = OrderDetails(order_id=order28.id, product_id=product5.product_id, quantity=14, unit_price=product5.price)
    db.session.add(order_detail28_2)
    order29 = SaleOrder(customer_id=customer5.customer_id, order_date=datetime.strptime('2024-08-29', '%Y-%m-%d').date(), total_amount=product5.price * 14 + product6.price * 15,
                            employee_id=employee4.employee_id)
    db.session.add(order29)
    db.session.commit()
    order_detail29 = OrderDetails(order_id=order29.id, product_id=product5.product_id, quantity=14, unit_price=product5.price)
    db.session.add(order_detail29)
    order_detail29_2 = OrderDetails(order_id=order29.id, product_id=product6.product_id, quantity=15, unit_price=product6.price)
    db.session.add(order_detail29_2)
    order30 = SaleOrder(customer_id=customer6.customer_id, order_date=datetime.strptime('2024-08-30', '%Y-%m-%d').date(), total_amount=product6.price * 10 + product7.price * 15,
                            employee_id=employee5.employee_id)
    db.session.add(order30)
    db.session.commit()
    order_detail30 = OrderDetails(order_id=order30.id, product_id=product6.product_id, quantity=10, unit_price=product6.price)
    db.session.add(order_detail30)
    order_detail30_2 = OrderDetails(order_id=order30.id, product_id=product7.product_id, quantity=15, unit_price=product7.price)
    db.session.add(order_detail30_2)
    order31 = SaleOrder(customer_id=customer7.customer_id, order_date=datetime.strptime('2024-05-30', '%Y-%m-%d').date(), total_amount=product7.price * 15 + product8.price * 15,
                            employee_id=employee1.employee_id)
    db.session.add(order31)
    db.session.commit()
    order_detail31 = OrderDetails(order_id=order31.id, product_id=product7.product_id, quantity=15, unit_price=product7.price)
    db.session.add(order_detail31)
    order_detail31_2 = OrderDetails(order_id=order31.id, product_id=product8.product_id, quantity=15, unit_price=product8.price)
    db.session.add(order_detail31_2)
    order32 = SaleOrder(customer_id=customer8.customer_id, order_date=datetime.strptime('2024-05-31', '%Y-%m-%d').date(), total_amount=product8.price * 10 + product9.price * 16,
                            employee_id=employee2.employee_id)
    db.session.add(order32)
    db.session.commit()
    order_detail32 = OrderDetails(order_id=order32.id, product_id=product8.product_id, quantity=10, unit_price=product8.price)
    db.session.add(order_detail32)
    order_detail32_2 = OrderDetails(order_id=order32.id, product_id=product9.product_id, quantity=16, unit_price=product9.price)
    db.session.add(order_detail32_2)
    order33 = SaleOrder(customer_id=customer9.customer_id, order_date=datetime.strptime('2024-09-09', '%Y-%m-%d').date(), total_amount=product9.price * 16 + product10.price * 15,
                            employee_id=employee3.employee_id)
    db.session.add(order33)
    db.session.commit()
    order_detail33 = OrderDetails(order_id=order33.id, product_id=product9.product_id, quantity=16, unit_price=product9.price)
    db.session.add(order_detail33)
    order_detail33_2 = OrderDetails(order_id=order33.id, product_id=product10.product_id, quantity=15, unit_price=product10.price)
    db.session.add(order_detail33_2)
    order34 = SaleOrder(customer_id=customer10.customer_id, order_date=datetime.strptime('2024-09-10', '%Y-%m-%d').date(), total_amount=product10.price * 17 + product11.price * 17,
                            employee_id=employee4.employee_id)
    db.session.add(order34)
    db.session.commit()
    order_detail34 = OrderDetails(order_id=order34.id, product_id=product10.product_id, quantity=17, unit_price=product10.price)
    db.session.add(order_detail34)
    order_detail34_2 = OrderDetails(order_id=order34.id, product_id=product11.product_id, quantity=17, unit_price=product11.price)
    db.session.add(order_detail34_2)
    order35 = SaleOrder(customer_id=customer11.customer_id, order_date=datetime.strptime('2024-09-11', '%Y-%m-%d').date(), total_amount=product11.price * 15 + product12.price * 17,
                            employee_id=employee5.employee_id)
    db.session.add(order35)
    db.session.commit()
    order_detail35 = OrderDetails(order_id=order35.id, product_id=product11.product_id, quantity=15, unit_price=product11.price)
    db.session.add(order_detail35)
    order_detail35_2 = OrderDetails(order_id=order35.id, product_id=product12.product_id, quantity=17, unit_price=product12.price)
    db.session.add(order_detail35_2)
    order36 = SaleOrder(customer_id=customer12.customer_id, order_date=datetime.strptime('2024-09-12', '%Y-%m-%d').date(), total_amount=product12.price * 18 + product1.price * 10,
                            employee_id=employee1.employee_id)
    db.session.add(order36)
    db.session.commit()
    order_detail36 = OrderDetails(order_id=order36.id, product_id=product12.product_id, quantity=18, unit_price=product12.price)
    db.session.add(order_detail36)
    order_detail36_2 = OrderDetails(order_id=order36.id, product_id=product1.product_id, quantity=10, unit_price=product1.price)
    db.session.add(order_detail36_2)
    order37 = SaleOrder(customer_id=customer1.customer_id, order_date=datetime.strptime('2024-09-13', '%Y-%m-%d').date(), total_amount=product1.price * 18 + product2.price * 18,
                            employee_id=employee2.employee_id)
    db.session.add(order37)
    db.session.commit()
    order_detail37 = OrderDetails(order_id=order37.id, product_id=product1.product_id, quantity=18, unit_price=product1.price)
    db.session.add(order_detail37)
    order_detail37_2 = OrderDetails(order_id=order37.id, product_id=product2.product_id, quantity=18, unit_price=product2.price)
    db.session.add(order_detail37_2)
    order38 = SaleOrder(customer_id=customer2.customer_id, order_date=datetime.strptime('2024-09-14', '%Y-%m-%d').date(), total_amount=product2.price * 19 + product3.price * 19,
                            employee_id=employee3.employee_id)
    db.session.add(order38)
    db.session.commit()
    order_detail38 = OrderDetails(order_id=order38.id, product_id=product2.product_id, quantity=19, unit_price=product2.price)
    db.session.add(order_detail38)
    order_detail38_2 = OrderDetails(order_id=order38.id, product_id=product3.product_id, quantity=19, unit_price=product3.price)
    db.session.add(order_detail38_2)
    order39 = SaleOrder(customer_id=customer3.customer_id, order_date=datetime.strptime('2024-09-15', '%Y-%m-%d').date(), total_amount=product3.price * 19 + product4.price * 19,
                            employee_id=employee4.employee_id)
    db.session.add(order39)
    db.session.commit()
    order_detail39 = OrderDetails(order_id=order39.id, product_id=product3.product_id, quantity=19, unit_price=product3.price)
    db.session.add(order_detail39)
    order_detail39_2 = OrderDetails(order_id=order39.id, product_id=product4.product_id, quantity=19, unit_price=product4.price)
    db.session.add(order_detail39_2)
    db.session.commit()
    order40 = SaleOrder(customer_id=customer4.customer_id, order_date=datetime.strptime('2024-04-16', '%Y-%m-%d').date(), total_amount=product4.price * 20 + product5.price * 20,
                            employee_id=employee5.employee_id)
    db.session.add(order40)
    db.session.commit()
    order_detail40 = OrderDetails(order_id=order40.id, product_id=product4.product_id, quantity=20, unit_price=product4.price)
    db.session.add(order_detail40)
    order_detail40_2 = OrderDetails(order_id=order40.id, product_id=product5.product_id, quantity=20, unit_price=product5.price)
    db.session.add(order_detail40_2)
    db.session.commit()
    order41 = SaleOrder(customer_id=customer5.customer_id, order_date=datetime.strptime('2024-03-17', '%Y-%m-%d').date(), total_amount=product5.price * 20 + product6.price * 20,
                            employee_id=employee1.employee_id)
    db.session.add(order41)
    db.session.commit()
    order_detail41 = OrderDetails(order_id=order41.id, product_id=product5.product_id, quantity=20, unit_price=product5.price)
    db.session.add(order_detail41)
    order_detail41_2 = OrderDetails(order_id=order41.id, product_id=product6.product_id, quantity=20, unit_price=product6.price)
    db.session.add(order_detail41_2)
    order42 = SaleOrder(customer_id=customer6.customer_id, order_date=datetime.strptime('2024-02-18', '%Y-%m-%d').date(), total_amount=product6.price * 21 + product7.price * 21,
                            employee_id=employee2.employee_id)
    db.session.add(order42)
    db.session.commit()
    order_detail42 = OrderDetails(order_id=order42.id, product_id=product6.product_id, quantity=21, unit_price=product6.price)
    db.session.add(order_detail42)
    order_detail42_2 = OrderDetails(order_id=order42.id, product_id=product7.product_id, quantity=21, unit_price=product7.price)
    db.session.add(order_detail42_2)
    order43 = SaleOrder(customer_id=customer7.customer_id, order_date=datetime.strptime('2024-01-19', '%Y-%m-%d').date(), total_amount=product7.price * 21 + product8.price * 21,
                            employee_id=employee3.employee_id)
    db.session.add(order43)
    db.session.commit()
    order_detail43 = OrderDetails(order_id=order43.id, product_id=product7.product_id, quantity=21, unit_price=product7.price)
    db.session.add(order_detail43)
    order_detail43_2 = OrderDetails(order_id=order43.id, product_id=product8.product_id, quantity=21, unit_price=product8.price)
    db.session.add(order_detail43_2)
    order44 = SaleOrder(customer_id=customer8.customer_id, order_date=datetime.strptime('2024-01-20', '%Y-%m-%d').date(), total_amount=product8.price * 22 + product9.price * 22,
                            employee_id=employee4.employee_id)
    db.session.add(order44)
    db.session.commit()
    order_detail44 = OrderDetails(order_id=order44.id, product_id=product8.product_id, quantity=22, unit_price=product8.price)
    db.session.add(order_detail44)
    order_detail44_2 = OrderDetails(order_id=order44.id, product_id=product9.product_id, quantity=22, unit_price=product9.price)
    db.session.add(order_detail44_2)
    order45 = SaleOrder(customer_id=customer9.customer_id, order_date=datetime.strptime('2024-06-21', '%Y-%m-%d').date(), total_amount=product9.price * 22 + product10.price * 22,
                            employee_id=employee5.employee_id)
    db.session.add(order45)
    db.session.commit()
    order_detail45 = OrderDetails(order_id=order45.id, product_id=product9.product_id, quantity=22, unit_price=product9.price)
    db.session.add(order_detail45)
    order_detail45_2 = OrderDetails(order_id=order45.id, product_id=product10.product_id, quantity=22, unit_price=product10.price)
    db.session.add(order_detail45_2)
    order46 = SaleOrder(customer_id=customer10.customer_id, order_date=datetime.strptime('2024-06-22', '%Y-%m-%d').date(), total_amount=product10.price * 23 + product11.price * 23,
                            employee_id=employee1.employee_id)
    db.session.add(order46)
    db.session.commit()
    order_detail46 = OrderDetails(order_id=order46.id, product_id=product10.product_id, quantity=23, unit_price=product10.price)
    db.session.add(order_detail46)
    order_detail46_2 = OrderDetails(order_id=order46.id, product_id=product11.product_id, quantity=23, unit_price=product11.price)
    db.session.add(order_detail46_2)
    order47 = SaleOrder(customer_id=customer11.customer_id, order_date=datetime.strptime('2024-06-23', '%Y-%m-%d').date(), total_amount=product11.price * 23 + product12.price * 23,
                            employee_id=employee2.employee_id)
    db.session.add(order47)
    db.session.commit()
    order_detail47 = OrderDetails(order_id=order47.id, product_id=product11.product_id, quantity=23, unit_price=product11.price)
    db.session.add(order_detail47)
    order_detail47_2 = OrderDetails(order_id=order47.id, product_id=product12.product_id, quantity=23, unit_price=product12.price)
    db.session.add(order_detail47_2)
    order48 = SaleOrder(customer_id=customer12.customer_id, order_date=datetime.strptime('2024-04-24', '%Y-%m-%d').date(), total_amount=product12.price * 24 + product1.price * 24,
                            employee_id=employee3.employee_id)
    db.session.add(order48)
    db.session.commit()
    order_detail48 = OrderDetails(order_id=order48.id, product_id=product12.product_id, quantity=24, unit_price=product12.price)
    db.session.add(order_detail48)
    order_detail48_2 = OrderDetails(order_id=order48.id, product_id=product1.product_id, quantity=24, unit_price=product1.price)
    db.session.add(order_detail48_2)
    db.session.commit()
    order49 = SaleOrder(customer_id=customer1.customer_id, order_date=datetime.strptime('2025-01-01', '%Y-%m-%d').date(), total_amount=product1.price * 24 + product2.price * 24,
                            employee_id=employee4.employee_id)
    db.session.add(order49)
    db.session.commit()
    order_detail49 = OrderDetails(order_id=order49.id, product_id=product1.product_id, quantity=24, unit_price=product1.price)
    db.session.add(order_detail49)
    order_detail49_2 = OrderDetails(order_id=order49.id, product_id=product2.product_id, quantity=245, unit_price=product2.price)
    db.session.add(order_detail49_2)
    order50 = SaleOrder(customer_id=customer2.customer_id, order_date=datetime.strptime('2025-01-02', '%Y-%m-%d').date(), total_amount=product2.price * 25 + product3.price * 25,
                            employee_id=employee5.employee_id)
    db.session.add(order50)
    db.session.commit()
    order_detail50 = OrderDetails(order_id=order50.id, product_id=product2.product_id, quantity=25, unit_price=product2.price)
    db.session.add(order_detail50)
    order_detail50_2 = OrderDetails(order_id=order50.id, product_id=product3.product_id, quantity=25, unit_price=product3.price)
    db.session.add(order_detail50_2)
    order51 = SaleOrder(customer_id=customer3.customer_id, order_date=datetime.strptime('2025-01-03', '%Y-%m-%d').date(), total_amount=product3.price * 25 + product4.price * 25,
                            employee_id=employee1.employee_id)
    db.session.add(order51)
    db.session.commit()
    order_detail51 = OrderDetails(order_id=order51.id, product_id=product3.product_id, quantity=25, unit_price=product3.price)
    db.session.add(order_detail51)
    order_detail51_2 = OrderDetails(order_id=order51.id, product_id=product4.product_id, quantity=25, unit_price=product4.price)
    db.session.add(order_detail51_2)
    order52 = SaleOrder(customer_id=customer4.customer_id, order_date=datetime.strptime('2025-01-04', '%Y-%m-%d').date(), total_amount=product4.price * 26 + product5.price * 26,
                            employee_id=employee2.employee_id)
    db.session.add(order52)
    db.session.commit()
    order_detail52 = OrderDetails(order_id=order52.id, product_id=product4.product_id, quantity=260, unit_price=product4.price)
    db.session.add(order_detail52)
    order_detail52_2 = OrderDetails(order_id=order52.id, product_id=product5.product_id, quantity=260, unit_price=product5.price)
    db.session.add(order_detail52_2)
# Generate orders cho  7 ngày gần nhất
    today = datetime.now()
    for i in range(7):
        order_date = today - timedelta(days=i)
        order_53 = SaleOrder(customer_id=customer1.customer_id, order_date=order_date, total_amount=product1.price * 5,
                          employee_id=employee1.employee_id)
        db.session.add(order_53)
        db.session.commit()
        order_detail = OrderDetails(order_id=order_53.id, product_id=product1.product_id, quantity=5, unit_price=product1.price)
        db.session.add(order_detail)
        db.session.commit()
        order_54 = SaleOrder(customer_id=customer2.customer_id, order_date=order_date, total_amount=product2.price * 10,
                          employee_id=employee2.employee_id)
        db.session.add(order_54)
        db.session.commit()
        order_detail = OrderDetails(order_id=order_54.id, product_id=product2.product_id, quantity=10, unit_price=product2.price)
        db.session.add(order_detail)
        db.session.commit()
        order_55 = SaleOrder(customer_id=customer3.customer_id, order_date=order_date, total_amount=product3.price * 15,
                          employee_id=employee1.employee_id)
        db.session.add(order_55)
        db.session.commit()
        order_detail = OrderDetails(order_id=order_55.id, product_id=product3.product_id, quantity=15, unit_price=product3.price)
        db.session.add(order_detail)
        db.session.commit()
        order_56 = SaleOrder(customer_id=customer4.customer_id, order_date=order_date, total_amount=product4.price * 20,
                          employee_id=employee3.employee_id)
        db.session.add(order_56)
        db.session.commit()
        order_detail = OrderDetails(order_id=order_56.id, product_id=product4.product_id, quantity=20, unit_price=product4.price)
        db.session.add(order_detail)
        db.session.commit()
        order_57 = SaleOrder(customer_id=customer5.customer_id, order_date=order_date, total_amount=product5.price * 25,
                          employee_id=employee4.employee_id)
        db.session.add(order_57)
        db.session.commit()
        order_detail = OrderDetails(order_id=order_57.id, product_id=product5.product_id, quantity=25, unit_price=product5.price)
        db.session.add(order_detail)
        db.session.commit()
        order_58 = SaleOrder(customer_id=customer6.customer_id, order_date=order_date, total_amount=product6.price * 30,
                          employee_id=employee5.employee_id)
        db.session.add(order_58)
        db.session.commit()
        order_detail = OrderDetails(order_id=order_58.id, product_id=product6.product_id, quantity=30, unit_price=product6.price)
        db.session.add(order_detail)
        db.session.commit()
        order_59 = SaleOrder(customer_id=customer7.customer_id, order_date=order_date, total_amount=product7.price * 35,
                          employee_id=employee1.employee_id)
        db.session.add(order_59)
        db.session.commit()
        order_detail = OrderDetails(order_id=order_59.id, product_id=product7.product_id, quantity=35, unit_price=product7.price)


